//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC2
    {
        public int IdSprzetu { get; set; }
        public string Nazwa { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
    }
}
